### ISSUE TITLE
Cast boolean from env variable

### ISSUE THREAD

**Issue by mhf-ir** [fastify/env-schema#70]
There is no type in env variable so for that how deal with casting boolean type ?

```js
const envSchema = require('env-schema').default;

const schema = {
  type: 'object',
  properties: {
    BOOL_VAL: {
      type: 'boolean',
    },
  },
};

['0', 'f', 'F', 'false', 'FALSE', 'False'].forEach((v) => {
  const r = envSchema({
    schema,
    data: {
      BOOL_VAL: v,
    },
  });
  console.log(r.BOOL_VAL === false);
});

['1', 't', 'T', 'true', 'TRUE', 'True'].forEach((v) => {
  const r = envSchema({
    schema,
    data: {
      BOOL_VAL: v,
    },
  });
  console.log(r.BOOL_VAL === true);
});

/**
Error: should be boolean
    at loadAndValidateEnvironment (./node_modules/env-schema/index.js:97:19)
    at ./test.js:13:13
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (./test.js:12:44)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  errors: [
    {
      keyword: 'type',
      dataPath: '/BOOL_VAL',
      schemaPath: '#/properties/BOOL_VAL/type',
      params: { type: 'boolean' },
      message: 'should be boolean'
    }
  ]
}
 */
```

Sample golang source code:
https://golang.org/src/strconv/atob.go#L10

JSs Implementation:
https://github.com/validatorjs/validator.js/blob/master/src/lib/toBoolean.js

**Comment by climba03003** [comment]
Please check the `Type coercion rules` for `ajv`. https://ajv.js.org/coercion.html#type-coercion-rules
The supported coercion for `boolean` are `1`, `0`, `true`, `false` and `null`.

**Comment by mhf-ir** [comment]
@climba03003 It's already set, seems not affected: https://github.com/fastify/env-schema/blob/master/index.js#L52
Run my example
